# Generated by Django 5.2 on 2025-04-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='refills_allowed',
        ),
        migrations.AddField(
            model_name='prescription',
            name='condition',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='controlled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-30 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='exp_date',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='refill',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
