# Generated by Django 5.2 on 2025-04-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_notes_prescription_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='controlled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='days_supply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='refill',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
