# Generated by Django 5.2 on 2025-05-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prescription_sent_to_pharmacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='controlled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
