# Generated by Django 5.2 on 2025-05-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_prescription_controlled'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='was_substituted',
            field=models.BooleanField(default=False),
        ),
    ]
