# Generated by Django 5.2 on 2025-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prescription_was_substituted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
        ),
    ]
